port: "9080"
ip_filter: false
banner: true
HTTP_response: true
# Only en or ja languages ​​are supported
language: "en"
ip_filter_path: "config/ip_filter.json"
cloud_data_path: "data/cloud_data.json"
